export const cidades = [
    {key: '1', value: 'Alvarães'},
    {key: '2', value: 'Amaturá'},
    {key: '3', value: 'Anamã'},
    {key: '4', value: 'Anori'},
    {key: '5', value: 'Apuí'},
    {key: '6', value: 'Atalaia do Norte'},
    {key: '7', value: 'Autazes'},
    {key: '8', value: 'Barcelos'},
    {key: '9', value: 'Barreirinha'},
    {key: '10', value: 'Benjamin Constant'},
    {key: '11', value: 'Beruri'},
    {key: '12', value: 'Boa Vista do Ramos'},
    {key: '13', value: 'Boca do Acre'},
    {key: '14', value: 'Borba'},
    {key: '15', value: 'Caapiranga'},
    {key: '16', value: 'Canutama'},
    {key: '17', value: 'Carauari'},
    {key: '18', value: 'Careiro'},
    {key: '19', value: 'Careiro da Várzea'},
    {key: '20', value: 'Coari'},
    {key: '21', value: 'Codajás'},
    {key: '22', value: 'Eirunepé'},
    {key: '23', value: 'Envira'},
    {key: '24', value: 'Fonte Boa'},
    {key: '25', value: 'Guajará'},
    {key: '26', value: 'Humaitá'},
    {key: '27', value: 'Ipixuna'},
    {key: '28', value: 'Iranduba'},
    {key: '29', value: 'Itacoatiara'},
    {key: '30', value: 'Itamarati'},
    {key: '31', value: 'Itapiranga'},
    {key: '32', value: 'Japurá'},
    {key: '33', value: 'Juruá'},
    {key: '34', value: 'Jutaí'},
    {key: '35', value: 'Lábrea'},
    {key: '36', value: 'Manacapuru'},
    {key: '37', value: 'Manaquiri'},
    {key: '38', value: 'Manaus'},
    {key: '39', value: 'Manicoré'},
    {key: '40', value: 'Maraã'},
    {key: '41', value: 'Maués'},
    {key: '42', value: 'Nhamundá'},
    {key: '43', value: 'Nova Olinda do Norte'},
    {key: '44', value: 'Novo Airão'},
    {key: '45', value: 'Novo Aripuanã'},
    {key: '46', value: 'Parintins'},
    {key: '47', value: 'Pauini'},
    {key: '48', value: 'Presidente Figueiredo'},
    {key: '49', value: 'Rio Preto da Eva'},
    {key: '50', value: 'Santa Isabel do Rio Negro'},
    {key: '51', value: 'Santo Antônio do Içá'},
    {key: '52', value: 'São Gabriel da Cachoeira'},
    {key: '53', value: 'São Paulo de Olivença'},
    {key: '54', value: 'São Sebastião do Uatumã'},
    {key: '55', value: 'Silves'},
    {key: '56', value: 'Tabatinga'},
    {key: '57', value: 'Tapauá'},
    {key: '58', value: 'Tefé'},
    {key: '59', value: 'Tonantins'},
    {key: '60', value: 'Uarini'},
    {key: '61', value: 'Urucará'},
    {key: '62', value: 'Urucurituba'},
]